version: '3.4'

services:
  productjudgeapi:
    image: ${DOCKER_REGISTRY-}productjudgeapi
    build:
      context: .
      dockerfile: ProductJudgeAPI/Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password

