name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '.github/workflows/cd-mobile.yml'
      - 'ProductJudgeMobile/ProductJudge.Mobile.DAL/**'
      - 'ProductJudgeMobile/ProductJudgeMobile/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build ProductJudgeAPI/ProductJudgeAPI/ProductJudgeAPI.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ProductJudgeAPI/ProductJudgeAPI/ProductJudgeAPI.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'productjudgetest2'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D2FC8103292E42068C7CF1B4452AEB48 }}
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3

  #   - name: Log in to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}

  #   - name: Build and push Docker image
  #     uses: docker/build-push-action@v6
  #     with:
  #       push: true
  #       tags: ${{ secrets.DOCKER_USERNAME }}/productjudgeapitest:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Deploy to Azure Web App
  #     id: deploy-to-webapp
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: 'testproductjudge'
  #       slot-name: 'production'
  #       publish-profile: ${{ secrets.AzureAppService_PublishProfile_258b220c509f4c088723d95266c7af57 }}
  #       images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/productjudgeapitest:latest'