name: CD Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '.github/workflows/cd-api.yml'
      - 'ProductJudgeAPI/**'

env:
  DOTNET_VERSION: 10.0.100-preview.2
  DOTNET_VERSION_TARGETS: net10.0
  BUILD_VERSION: '0.0'
  CSPROJ_TO_BUILD: ProductJudgeMobile/ProductJudgeMobile/ProductJudgeMobile.csproj
  PROJECT_FOLDER: ProductJudgeMobile/ProductJudgeMobile

jobs:
  vars:
    runs-on: ubuntu-24.04
    outputs:      
      buildVersion: ${{ env.BUILD_VERSION }}
      dotnetVersion: ${{ env.DOTNET_VERSION }}
      dotnetVersionTargets: ${{ env.DOTNET_VERSION_TARGETS }}
      csprojToBuild: ${{ env.CSPROJ_TO_BUILD }}
      projectFolder: ${{ env.PROJECT_FOLDER }}
    steps:
      - run: echo "Exposing env vars, because they can't be passed to nested workflows."

  build-android:
    needs: vars
    uses: ./.github/workflows/cd-android.template.yml
    with:
      dotnet-version: ${{ needs.vars.outputs.dotnetVersion }}
      dotnet-version-target: ${{ needs.vars.outputs.dotnetVersionTargets }}
      project-file: ${{ needs.vars.outputs.csprojToBuild }}
      project-folder: ${{ needs.vars.outputs.projectFolder }}
      build-config: 'Release'
      build-version: ${{ needs.vars.outputs.buildVersion }}
    secrets:
      keystore: ${{ secrets.ANDROID_KEYSTORE }}
      keystore-alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
      keystore-password: ${{ secrets.ANDROID_KEYSTORE_PASS }}

  distribute-firebase:
   needs: build-android
   uses: ./.github/workflows/firebase-distribution.template.yml
   secrets:
      firebase_app_id: ${{ secrets.firebase_app_id}}
      firebase_service_account: ${{ secrets.firebase_service_account }}